export const GET_CLIENT = 'GET_CLIENT';
export const GET_CLIENT_SUCCESS = 'GET_CLIENT_SUCCESS';
export const GET_CLIENT_FAIL = 'GET_CLIENT_FAIL';

export const UPDATE_CLIENT_PRODUCT_AVAILABILITY = 'UPDATE_CLIENT_PRODUCT_AVAILABILITY';
export const UPDATE_CLIENT_PRODUCT_AVAILABILITY_SUCCESS = 'UPDATE_CLIENT_PRODUCT_AVAILABILITY_SUCCESS';
export const UPDATE_CLIENT_PRODUCT_AVAILABILITY_FAIL = 'UPDATE_CLIENT_PRODUCT_AVAILABILITY_FAIL';

export const REMOVE_CLIENT_PRODUCT = 'REMOVE_CLIENT_PRODUCT';
export const REMOVE_CLIENT_PRODUCT_SUCCESS = 'REMOVE_CLIENT_PRODUCT_SUCCESS';
export const REMOVE_CLIENT_PRODUCT_FAIL = 'REMOVE_CLIENT_PRODUCT_FAIL';
export const SAVE_CLIENT_PRODUCT = 'SAVE_CLIENT_PRODUCT';
export const SAVE_CLIENT_PRODUCT_FAIL = 'SAVE_CLIENT_PRODUCT_FAIL';

export const TOGGLE_EDIT_MODE = 'TOGGLE_EDIT_MODE';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const FILTER_BY_NAME = 'FILTER_BY_NAME';
export const SORT = 'SORT';

export const GET_TEXTS = 'GET_TEXTS';
export const GET_TEXTS_SUCCESS = 'GET_TEXTS_SUCCESS';
export const GET_TEXTS_FAIL = 'GET_TEXTS_FAIL';

export const UPDATE_TEXTS = 'UPDATE_TEXTS';
export const UPDATE_TEXTS_SUCCESS = 'UPDATE_TEXTS_SUCCESS';
export const UPDATE_TEXTS_FAIL = 'UPDATE_TEXTS_FAIL';

export const REFRESH_TEXTS = 'REFRESH_TEXTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const TOGGLE_SELECT_CLIENT_MODAL = 'TOGGLE_SELECT_CLIENT_MODAL';
export const SET_CLIENTS_META = 'SET_CLIENTS_META';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';
